package dev.daanh.zombie.domain.location.enums;

public enum LocationType {
    
    // OSM LOCATIONS

    HOSPITAL, CLINIC, PHARMACY, DEFIBRILLATOR,
    
    SUPERMARKET, GENERAL_STORE, RESTAURANT, FAST_FOOD, CAFE, PUB, BAKERY, HAIRDRESSER, CAR_REPAIR, GAS_STATION,
    
    POLICE_STATION, FIRE_STATION, TOWN_HALL,
    
    SCHOOL, UNIVERSITY,
    
    CHURCH, CEMETERY,
    
    PARK, PITCH, PLAYGROUND, CAMPSITE,
    
    BENCH, WASTE_BASKET, WASTE_DISPOSAL, RECYCLING, FIRE_HYDRANT, POST_BOX, DRINKING_WATER, TOILETS, VENDING_MACHINE, ATM,
    
    // CUSTOM LOCATIONS

    HOUSE, APARTMENT_BUILDING, HOTEL, FARM, CABIN,
    
    WAREHOUSE, FACTORY, WORKSHOP, CONSTRUCTION_SITE,
    
    TRAIN_STATION, BUS_STATION, AIRPORT, PORT, PARKING_LOT,
    
    POWER_PLANT, WATER_TREATMENT_PLANT, RADIO_TOWER, ROAD, BRIDGE, TUNNEL,
    
    MILITARY_BASE, CHECKPOINT, BUNKER, SAFEHOUSE, SHELTER, RUINS,
    
    UNKNOWN
}
