services:
  postgres:
    image: postgres:16-alpine
    container_name: zombiedb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zombiedb
    volumes:
      - zombiedb-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  zombiedb-data: