spring:
  application:
    name: zombie
  
  datasource:
    url: jdbc:postgresql://localhost:5432/zombiedb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      format_sql: false
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500
          batch_versioned_data: true

game:
  world:
    chunk-size-km: 1.0
    name: "Earth"
    default-seed: 42
    chunk:
      chunk-generation-radius: 5
      maximum-chunk-cache-size: 10_000
  simulation:
    tick-rate-ms: 1000
    minutes-per-tick: 1
    start-time: "2026-01-01T00:00:00Z"
